/*

Given a string of length n, generate all of its subsequences.

A subsequence of a given string (sequence) is a string (sequence) that is generated by
removing zero or more characters from the given string (sequence) without changing its
order.

Example

	Input : inp[] = "abc"
	Output: ["", "c", "b", "bc", "a", "ac", "ab", "abc"]

Constraints

  1 < n < 10

*/

#include<iostream>
#include<set>

using namespace std;

void f(char inp[], char out[], int i, int j, set<string>& s) {

	// base case

	if (inp[i] == '\0') { // i == n

		out[j] = '\0';
		// cout << out << endl;

		// string outSubSeq(out);
		// s.insert(outSubSeq);

		s.insert(string(out));

		return;

	}

	// recursive case

	// generate all the subseq for suffix of inp[] that starts at the ith index

	// or

	// take a sequence of n-i decisions for the characters in the inp[] from i to n-1

	// take a decision for inp[i]

	// option 1 : include inp[i] in the out[]

	out[j] = inp[i];
	f(inp, out, i + 1, j + 1, s);

	// option 2 : exclude inp[i] from the out[]

	f(inp, out, i + 1, j, s);

}

int main() {

	char inp[] = "abc";
	char out[10];

	set<string> s;

	f(inp, out, 0, 0, s);

	cout << s.size() << endl;

	for (string outSubSeq : s) {
		cout << outSubSeq << endl;
	}

	return 0;
}
